if(!pokedex.moves)pokedex.moves={};
if(!pokedex.moves.effect)pokedex.moves.effect=[];
pokedex.moves.effect[1] = {
2:"Has an increased chance for a critical hit.",
6:"Scatters money on the ground worth two times the user's level.",
18:"Immediately ends wild battles.",
20:"Prevents the opponent from attacking and inflicts damage for 2-5 turns.",
26:"If the user misses, it loses 1 HP.",
35:"Prevents the opponent from attacking and inflicts damage for 2-5 turns.",
38:"User receives 1/4 the damage inflicted in recoil.",
46:"Immediately ends wild battles.",
50:"Prevents a random move of the target from being used again for 0-6 turns.",
51:"Has a $effect_chance% chance to lower the target's Defense by one level.",
74:"Boosts user's Special by one stage.",
75:"Has an increased chance for a critical hit.",
76:"Requires a turn to charge before attacking. During Sunny Day, this attack takes one turn.",
83:"Prevents the opponent from attacking and inflicts damage for 2-5 turns.",
94:"Has a $effect_chance% chance to lower the target's Special by one level.",
99:"If the user is hit after using this move, its Attack rises by one level and you can't do anything until the user faints.",
102:"Copies a random move of the target.",
107:"Raises the user's Evasion.",
113:"Halves Special damage done to user.",
120:"Inflicts double damage and halves the target's Defense. User faints.",
128:"Prevents the opponent from attacking and inflicts damage for 2-5 turns.",
130:"Raises the user's Defense by one level. User charges for one turn before attacking.",
133:"Raises the user's Special by two levels.",
136:"If the user misses, it loses 1 HP.",
146:"Inflicts regular damage with no additional effect.",
152:"Has an increased chance for a critical hit.",
153:"Inflicts double damage and halves the target's Defense. User faints.",
156:"User sleeps for one turn, completely healing itself.",
161:"Inflicts regular damage with no additional effect.",
163:"Has an increased chance for a critical hit.",
164:"Transfers 1/4 of the user's max HP into a doll, protecting the user from further damage until it breaks.",
165:"User takes 1/2 its max HP in recoil.",
};